/**
 * @protected DO NOT MODIFY without running full regression suite
 * 
 * This module is used by: MenuDetector, CandidateFinder, Resolver, DOMMap, ScopeResolver
 * Changes here affect ALL workflows including:
 * - Gainsight widget detection
 * - SFDC navigation
 * - Shadow DOM traversal for web components
 * - Menu item extraction from portals
 * 
 * Before modifying, run: npm run test:integration
 * 
 * ShadowDOMUtils - Utilities for working with Shadow DOM
 */

export interface ShadowPath {
  hostSelector: string; // Selector for shadow host
  shadowRootIndex?: number; // If multiple shadow roots
  path: string; // Path within shadow DOM
}

export class ShadowDOMUtils {
  /**
   * Get shadow root if element is a shadow host
   */
  static getShadowRoot(element: Element): ShadowRoot | null {
    if (element.shadowRoot) {
      return element.shadowRoot;
    }
    return null;
  }
  
  /**
   * Shadow-aware closest() - like element.closest() but traverses shadow boundaries
   * This is critical for finding widgets/containers when element is in shadow DOM
   */
  static closestAcrossShadow(element: Element, selector: string): Element | null {
    let current: Element | null = element;
    
    // First, try standard closest() in current context
    const match = current.closest(selector);
    if (match) return match;
    
    // If not found and we're in a shadow root, continue from the shadow host
    const rootNode = element.getRootNode();
    if (rootNode !== document && 'host' in rootNode) {
      const shadowHost = (rootNode as ShadowRoot).host;
      console.log('[ShadowDOMUtils] 🌑 Element in shadow root, checking host and ancestors');
      
      // Check if shadow host matches
      if (shadowHost.matches(selector)) {
        return shadowHost;
      }
      
      // Continue searching from host's parent
      return shadowHost.closest(selector);
    }
    
    return null;
  }

  /**
   * Check if an element is inside Shadow DOM
   */
  static isInShadowDOM(element: Element): boolean {
    let current: Element | null = element;
    while (current) {
      if (current.getRootNode() instanceof ShadowRoot) {
        return true;
      }
      current = current.parentElement;
    }
    return false;
  }

  /**
   * Get the shadow host containing this element
   */
  static getShadowHost(element: Element): Element | null {
    let root = element.getRootNode();
    while (root && root !== document) {
      if (root instanceof ShadowRoot) {
        return root.host;
      }
      // If we're in a shadow root, get its host and check its root
      if (root instanceof DocumentFragment) {
        const host = (root as any).host;
        if (host) {
          root = host.getRootNode();
        } else {
          break;
        }
      } else {
        break;
      }
    }
    return null;
  }

  /**
   * Get path through shadow boundaries
   */
  static getShadowPath(element: Element): ShadowPath[] {
    const path: ShadowPath[] = [];
    let current: Element | null = element;

    while (current) {
      const shadowHost = this.getShadowHost(current);
      if (shadowHost) {
        // Generate selector for shadow host
        const hostSelector = this.generateHostSelector(shadowHost);
        // Generate path within shadow DOM
        const innerPath = this.generatePathInShadow(current, shadowHost);
        
        path.unshift({
          hostSelector,
          path: innerPath,
        });

        current = shadowHost;
      } else {
        break;
      }
    }

    return path;
  }

  /**
   * Generate a selector for the shadow host
   * CRITICAL: Only include STABLE class names - exclude framework-generated dynamic classes
   */
  private static generateHostSelector(host: Element): string {
    if (host.id) {
      return `#${CSS.escape(host.id)}`;
    }
    
    const tagName = host.tagName.toLowerCase();
    
    // CRITICAL: For custom elements (web components), just use the tag name!
    // Custom element tags like gs-report-widget-element are already unique
    // Adding dynamic classes like .ng-star-inserted causes replay failures
    if (tagName.includes('-')) {
      console.log(`[ShadowDOMUtils] 🌑 Using custom element tag name only: ${tagName}`);
      return tagName;
    }
    
    // For standard HTML elements, add stable class names only
    if (host.className && typeof host.className === 'string') {
      const classes = host.className
        .split(/\s+/)
        .filter((c) => c.length > 0)
        // CRITICAL: Filter out dynamic/framework-generated classes
        .filter((c) => !this.isDynamicClassName(c))
        .map((c) => `.${CSS.escape(c)}`)
        .join('');
      if (classes) {
        return `${tagName}${classes}`;
      }
    }
    
    return tagName;
  }
  
  /**
   * Check if a class name is dynamically generated by a framework
   * These classes should NOT be included in selectors as they may change between page loads
   */
  private static isDynamicClassName(className: string): boolean {
    // Angular dynamic classes
    if (className.startsWith('ng-')) return true;
    if (className === 'ng-star-inserted') return true;
    if (className === 'ng-scope') return true;
    if (className === 'ng-isolate-scope') return true;
    
    // React dynamic classes  
    if (className.startsWith('react-')) return true;
    
    // Vue dynamic classes
    if (className.startsWith('v-')) return true;
    if (className.startsWith('vue-')) return true;
    
    // CSS-in-JS/CSS Modules generated classes (random hashes)
    if (/^css-[a-z0-9]+$/i.test(className)) return true;
    if (/^_css-[a-z0-9]+$/i.test(className)) return true;
    if (/^sc-[a-z0-9]+$/i.test(className)) return true;  // styled-components
    if (/^emotion-[a-z0-9]+$/i.test(className)) return true;
    if (/^jss[0-9]+-[a-z0-9]+$/i.test(className)) return true;
    
    // Generic dynamic patterns (random alphanumeric suffixes)
    if (/^[a-z]+-[a-z0-9]{6,}$/i.test(className)) return true;
    
    // Material-UI generated classes
    if (/^Mui[A-Z]/.test(className)) return true;
    
    return false;
  }

  /**
   * Generate path to element within shadow DOM
   */
  private static generatePathInShadow(element: Element, shadowHost: Element): string {
    const parts: string[] = [];
    let current: Element | null = element;

    while (current && current !== shadowHost) {
      const tagName = current.tagName.toLowerCase();
      let selector = tagName;

      if (current.id) {
        selector += `#${CSS.escape(current.id)}`;
        parts.unshift(selector);
        break;
      }

      if (current.className && typeof current.className === 'string') {
        const classes = current.className
          .split(/\s+/)
          .filter((c) => c.length > 0)
          .map((c) => `.${CSS.escape(c)}`)
          .join('');
        if (classes) {
          selector += classes;
        }
      }

      // Count preceding siblings
      let index = 1;
      let sibling = current.previousElementSibling;
      while (sibling) {
        if (sibling.tagName.toLowerCase() === tagName) {
          index++;
        }
        sibling = sibling.previousElementSibling;
      }

      if (index > 1) {
        selector += `:nth-of-type(${index})`;
      }

      parts.unshift(selector);
      current = current.parentElement;
    }

    return parts.join(' > ');
  }

  /**
   * Find element within shadow DOM
   */
  static findElementInShadowDOM(host: Element, selector: string): Element | null {
    const shadowRoot = this.getShadowRoot(host);
    if (!shadowRoot) {
      return null;
    }

    try {
      return shadowRoot.querySelector(selector);
    } catch (error) {
      console.error('Error querying shadow DOM:', error);
      return null;
    }
  }

  /**
   * Recursively traverse all shadow roots
   */
  static traverseShadowDOM(
    root: Document | ShadowRoot,
    callback: (element: Element) => void
  ): void {
    const walker = document.createTreeWalker(
      root,
      NodeFilter.SHOW_ELEMENT,
      null
    );

    let node: Node | null = walker.nextNode();
    while (node) {
      if (node instanceof Element) {
        callback(node);

        // If this element has a shadow root, traverse it
        if (node.shadowRoot) {
          this.traverseShadowDOM(node.shadowRoot, callback);
        }
      }
      node = walker.nextNode();
    }
  }

  /**
   * Universal deep query - searches both light DOM and ALL shadow DOMs
   * 
   * This replaces duplicate implementations in MenuDetector and CandidateFinder.
   * Searches recursively through all shadow roots to find matching elements.
   * 
   * @param selector - CSS selector to match
   * @param root - Root element or document to start search from
   * @returns Array of all matching elements in light and shadow DOMs
   */
  static queryDeep(selector: string, root: Element | Document = document): Element[] {
    const results: Element[] = [];
    const rootElement = root instanceof Element ? root : null;
    
    // Phase 1: Search light DOM
    try {
      const lightDOMMatches = root.querySelectorAll(selector);
      results.push(...Array.from(lightDOMMatches));
    } catch (e) {
      // Invalid selector - continue with shadow DOM search
    }
    
    // Phase 2: Search all Shadow DOMs recursively
    // traverseShadowDOM expects Document or ShadowRoot, so get the document
    const docRoot = root instanceof Document ? root : root.ownerDocument || document;
    
    this.traverseShadowDOM(docRoot, (el) => {
      try {
        // If root is an Element, only include descendants of that element
        if (rootElement && !rootElement.contains(el)) {
          return; // Skip elements outside the root container
        }
        
        if (el.matches(selector)) {
          // Deduplicate - check if already in results
          if (!results.includes(el)) {
            results.push(el);
          }
        }
      } catch (e) {
        // Invalid selector or element - continue
      }
    });
    
    return results;
  }
  
  /**
   * Find first matching element across light and shadow DOMs
   * 
   * More efficient than queryDeep when you only need one result.
   * 
   * @param selector - CSS selector to match
   * @param root - Root element or document to start search from
   * @returns First matching element or null
   */
  static queryDeepFirst(selector: string, root: Element | Document = document): Element | null {
    const rootElement = root instanceof Element ? root : null;
    
    // Try light DOM first (faster)
    try {
      const lightMatch = root.querySelector(selector);
      if (lightMatch) return lightMatch;
    } catch (e) {
      // Invalid selector
    }
    
    // Search shadow DOMs
    let found: Element | null = null;
    const docRoot = root instanceof Document ? root : root.ownerDocument || document;
    
    this.traverseShadowDOM(docRoot, (el) => {
      if (found) return; // Already found, stop searching
      
      try {
        // If root is an Element, only include descendants of that element
        if (rootElement && !rootElement.contains(el)) {
          return;
        }
        
        if (el.matches(selector)) {
          found = el;
        }
      } catch (e) {
        // Invalid selector or element
      }
    });
    
    return found;
  }
}
